// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DocSeeker.API.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class DoctorServiceTestsFeature : object, Xunit.IClassFixture<DoctorServiceTestsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DoctorServiceTests.feature"
#line hidden
        
        public DoctorServiceTestsFeature(DoctorServiceTestsFeature.FixtureData fixtureData, DocSeeker_API_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "DoctorServiceTests", "\tAs a Doctor in the app,\r\n\tI want to be able to register an account\r\n\tIn order to" +
                    " be able to login and add information", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
 #line hidden
#line 7
  testRunner.Given("the Endpoint https://localhost:7263/api/v1/doctor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add new doctor account")]
        [Xunit.TraitAttribute("FeatureTitle", "DoctorServiceTests")]
        [Xunit.TraitAttribute("Description", "Add new doctor account")]
        [Xunit.TraitAttribute("Category", "doctor-adding")]
        public virtual void AddNewDoctorAccount()
        {
            string[] tagsOfScenario = new string[] {
                    "doctor-adding"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new doctor account", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 10
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "firstName",
                            "lastName",
                            "dni",
                            "password",
                            "genre",
                            "birthday",
                            "email",
                            "cell1",
                            "photo",
                            "area",
                            "description",
                            "patients",
                            "years",
                            "age",
                            "cost"});
                table1.AddRow(new string[] {
                            "Martin",
                            "Martinez",
                            "92734512",
                            "quieroamisgatos",
                            "male",
                            "17/12/1977",
                            "ernesto@gmail.com",
                            "993212755",
                            "profilePhoto.cloud.com",
                            "San Miguel",
                            "Doctor and nutrition",
                            "4",
                            "10",
                            "41",
                            "300"});
#line 11
  testRunner.When("a new Doctor is registered", ((string)(null)), table1, "When ");
#line hidden
#line 14
  testRunner.Then("the response code is 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "firstName",
                            "lastName",
                            "dni",
                            "password",
                            "genre",
                            "birthday",
                            "email",
                            "cell1",
                            "photo",
                            "area",
                            "description",
                            "patients",
                            "years",
                            "age",
                            "cost"});
                table2.AddRow(new string[] {
                            "Martin",
                            "Martinez",
                            "92734512",
                            "quieroamisgatos",
                            "male",
                            "17/12/1977",
                            "ernesto@gmail.com",
                            "993212755",
                            "profilePhoto.cloud.com",
                            "San Miguel",
                            "Doctor and nutrition",
                            "4",
                            "10",
                            "41",
                            "300"});
#line 15
  testRunner.And("a Doctor Resource is included in the Response Body", ((string)(null)), table2, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                DoctorServiceTestsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                DoctorServiceTestsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
